# Generated by Django 5.0.6 on 2024-06-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profilemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(default='', upload_to='avatar'),
            preserve_default=False,
        ),
    ]
